### ISSUE TITLE
Validar taules fq, indexsbio i estacions a CartoDB

### ISSUE THREAD

**Issue by mpericay** [mpericay/barcelonarius#1]
Comprovar que les dades estàn OK i que es poden fer mapes. Provar de fer un mapa antic (ex: 2013) amb un join de les tres taules i verificar que surt igual que el publicat.

**Comment by pfortuno** [comment]
dades taules fq i indexbio validades. 
- **FQ**: validació camps 'opcions sec' i 'cabal';
- **Indexsbio**: validació camp 'opcions sec' i afegits rangs IBMWP de mostres anteriors a 2008

**Comment by pfortuno** [comment]
SELECT e.estacio, e.cartodb_id,  e.the_geom_webmercator, b.ecostrimed, b.data FROM estacions e LEFT JOIN indexbio b ON e.estacio=b.estacio WHERE b.data < '2008-07-01'::date AND b.data > '2008-01-01'

**Comment by pfortuno** [comment]
- **estacions**: validat
- *_mapes *_creats: 
1. _estat ecològic primavera 2008_ 
   https://ub.cartodb.com/viz/b2054d84-db9a-11e5-82a4-0ecd1babdde5/public_map
   **SQL**: 
   SELECT e.estacio, e.cartodb_id, e.the_geom_webmercator, b.ecostrimed, b.data FROM estacions e LEFT JOIN indexbio b ON e.estacio=b.estacio WHERE b.data < '2008-07-01'::date AND b.data > '2008-01-01'
2. _Conductivitat primavera 2008_
   https://ub.cartodb.com/viz/e704e3d4-dba2-11e5-9d51-0e674067d321/public_map
   **SQL**: 
   SELECT e.estacio, e.cartodb_id,  e.the_geom_webmercator, b.cond, b.data FROM estacions e LEFT JOIN FQ b ON e.estacio=b.estacio WHERE b.data < '2008-07-01'::date AND b.data > '2008-01-01'
