### ISSUE TITLE
Afegir capes extra

### ISSUE THREAD

**Issue by mpericay** [mpericay/barcelonarius#10]

**Comment by mpericay** [comment]
Calen més capes?
http://territori.gencat.cat/ca/01_departament/11_normativa_i_documentacio/04_dades_obertes/cartografia_i_mapes/
Falta tipologies ACA?

**Comment by mpericay** [comment]
Capes:
- Rius: nostra, amb tipologies i nom
- Conques(6): nostra, amb etiquetes
- Depuradores
- Parcs
- Capa climàtica: buscar

**Comment by pfortuno** [comment]
tres capes a afegir o modificar les actuals:

rius_barcelona
embassaments_barcelona
limits_provincia_barcelona
conques_barcelona

he fet un mapa amb l'estil de com podria quedar:
https://ub.cartodb.com/viz/2ac606d4-330f-11e6-8f99-0e3ff518bd15/public_map

**Comment by pfortuno** [comment]
la capa depuradores fa molt que no funciona...haurem de buscar una solució o directament no posar-les.

**Comment by pfortuno** [comment]
capa EDAR

https://ub.cartodb.com/viz/803a141c-3471-11e6-af9d-0e674067d321/public_map

CSS de la visualització:
/*\* simple visualization */

#edar_2016{
  marker-file: url(http://com.cartodb.users-assets.production.s3.amazonaws.com/simpleicon/map51.svg);
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 1;
  marker-line-opacity: 1;
  marker-placement: point;
  marker-type: ellipse;
  marker-width: 8;
  marker-fill: #000000;
  marker-allow-overlap: true;
}

**Comment by pfortuno** [comment]
capa Xarxa Parcs Naturals

https://ub.cartodb.com/viz/ca9eb97e-3474-11e6-a0c5-0ea31932ec1d/public_map 

CSS de la visualització:
/*\* simple visualization */

#xpn1{
  polygon-fill: #055D00;
  polygon-opacity: 0.2;
  line-color: #FFF;
  line-width: 0.5;
  line-opacity: 1;
}
