### ISSUE TITLE
Decidir quins anys posem, i mirar si ajuntem anys

### ISSUE THREAD

**Issue by mpericay** [mpericay/barcelonarius#17]
Proves per

**Comment by pfortuno** [comment]
inventari d'anys, mesos i paramatres fet.
Proposo mostrar a l'slider:
1979
1980-1989 (anys units)
1990
1991-1994 (anys units)
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
