### ISSUE TITLE
Introduir dades 2015 a les taules fq, indexsbio i estacions

### ISSUE THREAD

**Issue by mpericay** [mpericay/barcelonarius#2]

**Comment by mpericay** [comment]
Comprovar que funcionen els scripts SELECT INTO

**Comment by pfortuno** [comment]
comprovat!

amb:

INSERT INTO FQ (the_geom, amoni, cabal, clorurs, cond, data, estacio, fosfats, nitrats, nitrits, oxigenmg, oxigenper, ph, sec, sulfats, temp) (SELECT the_geom, amoni, cabal, clorurs, cond, data, estacio, fosfats, nitrats, nitrits, oxigenmg, oxigenper, ph, sec, sulfats, temp FROM fq_primavera2015)

**Comment by mpericay** [comment]
Falten dades indexbio! Cal posar-les directament a carimed_historic_data

**Comment by pfortuno** [comment]
fet!!

INSERT INTO carimed_historic_data (cartodb_id, the_geom, s, qbr, ihf, ibmwp_rang, ibmwp, fbill, ecostrimed, bmwpc, bill, sec, conca, peixos, idmostreig, estacio, iaspt, epoca, ss, amoni, nitrits, nitrats, fosfats, fosfor, sulfats, clorurs, silicats, calci, Magnesi, sodi, Potasi, ferro, manganes, zinc, coure, crom, niquel, cobalt, dqo, clad, clo_a, cabal, ph, oxigenper, oxigenmg, temp, cond, data) (SELECT cartodb_id, the_geom, s, qbr, ihf, ibmwp_rang, ibmwp, fbill, ecostrimed, bmwpc, bill, sec, conca, peixos, idmostreig, estacio, iaspt, epoca, ss, amoni, nitrits, nitrats, fosfats, fosfor, sulfats, clorurs, silicats, calci, Magnesi, sodi, Potasi, ferro, manganes, zinc, coure, crom, niquel, cobalt, dqo, clad, clo_a, cabal, ph, oxigenper, oxigenmg, temp, cond, data FROM dades_carimed_2015)

**Comment by pfortuno** [comment]
totes les dades del 2015 es visualitzen bé menys les de l'estació SC19 (dintre de Collserola).
No apareix al mapa de 2015 i no sé a què pot ser degut. Al mapa de 2014 sí que apareix.
