### ISSUE TITLE
Afegir fotos al servidor

### ISSUE THREAD

**Issue by mpericay** [mpericay/barcelonarius#5]

**Comment by pfortuno** [comment]
afegides al directori **/barcelonarius/pictures_2015**
separades en dues carpetes: **primavera *_i *_estiu**

**Comment by mpericay** [comment]
A la taula carimedfotos2015 necessitem un camp 'data' per poder enllaçar amb indexsbio i fq

**Comment by mpericay** [comment]
Deixo oberta l'altra tasca
