### ISSUE TITLE
Taula fotos i proves

### ISSUE THREAD

**Issue by mpericay** [mpericay/barcelonarius#6]

**Comment by pfortuno** [comment]
he fet una taula a cartoDB (carimedfotos2015) amb algunes fotos.

**Comment by mpericay** [comment]
A la taula carimedfotos2015 necessitem un camp 'data' per poder enllaçar amb indexsbio i fq

**Comment by mpericay** [comment]
UPDATE indexbio b SET epoca=0 WHERE EXTRACT (MONTH FROM b.data) < 7
